version: '3.3'
services:
  redis:
    image: redis:alpine
    container_name: redis
    restart: unless-stopped
    networks:
      - book-reviews

  api:
    image: nileshkdev/book-reviews:api
    build: .
    ports:
      - "4000:4000"
    environment:
      REDIS_HOST: redis
    depends_on:
      - redis
      - worker
    networks:
      - book-reviews

  worker:
    image: nileshkdev/book-reviews:worker
    build: .
    environment:
      REDIS_HOST: redis
    depends_on:
      - redis
    networks:
      - book-reviews

networks:
  book-reviews:
